# Generated by Django 2.0.5 on 2018-05-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album_cover',
            field=models.ImageField(default='covers/no_image.png', upload_to='covers/%Y/%m/%d'),
        ),
    ]
