# Generated by Django 2.0.5 on 2018-05-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_albumtrackfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumtrackfiles',
            name='track_file',
            field=models.FileField(default='tracks/no_track.mp3', upload_to='tracks/%Y/%m/%d'),
        ),
    ]
