# Generated by Django 2.0.5 on 2018-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180526_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumtrackfiles',
            name='track_file',
            field=models.FileField(default='tracks/no_track.mp3', upload_to='tracks'),
        ),
        migrations.AlterField(
            model_name='post',
            name='album_cover',
            field=models.ImageField(default='covers/no_image.png', upload_to='covers'),
        ),
    ]
